services:
  db:
    container_name: "taskmanager-store"
    image: "postgres:13.3"
    ports:
      - 5433:5432
    volumes:
      - ./scripts/pg-init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=${DB_PROJECTS_NAME},${DB_USERS_NAME}
